---
- include_tasks: register.yml
  when: inventory_hostname in groups['trove-api']

- import_tasks: config.yml

- include_tasks: clone.yml
  when: trove_dev_mode | bool

- include_tasks: bootstrap.yml
  when: inventory_hostname in groups['trove-api']

- name: Flush handlers
  meta: flush_handlers
