---
- include_tasks: register.yml
  when: inventory_hostname in groups['karbor-api']

- import_tasks: config.yml

- include_tasks: bootstrap.yml
  when: inventory_hostname in groups['karbor-api']

- name: Flush handlers
  meta: flush_handlers
