---
- include_tasks: register.yml
  when: inventory_hostname in groups['murano-api']

- import_tasks: config.yml

- include_tasks: clone.yml
  when:
    - murano_dev_mode | bool

- include_tasks: bootstrap.yml
  when: inventory_hostname in groups['murano-api']

- name: Flush handlers
  meta: flush_handlers

- import_tasks: import_library_packages.yml
