---
- include_tasks: register.yml
  when: inventory_hostname in groups['ceilometer']

- import_tasks: config.yml

- include_tasks: clone.yml
  when: ceilometer_dev_mode | bool

- include_tasks: bootstrap.yml
  when: inventory_hostname in groups['ceilometer']

- name: Flush handlers
  meta: flush_handlers
