---
- include_tasks: register.yml
  when: inventory_hostname in groups['freezer-api']

- import_tasks: config.yml

- include_tasks: clone.yml
  when: freezer_dev_mode | bool

- include_tasks: bootstrap.yml
  when: freezer_database_backend == 'mariadb' and inventory_hostname in groups['freezer-api']

- include_tasks: bootstrap_service.yml
  when: inventory_hostname in groups['freezer-api']

- name: Flush handlers
  meta: flush_handlers
