---
- include_tasks: register.yml
  when: inventory_hostname in groups['monasca-agent'] or
        inventory_hostname in groups['monasca-api']

- import_tasks: config.yml

- include_tasks: bootstrap.yml
  when: inventory_hostname in groups['monasca-api'] or
        inventory_hostname in groups['monasca-grafana']

- name: Flush handlers
  meta: flush_handlers

- import_tasks: check.yml

- import_tasks: post_config.yml
